# Generated by Django 5.2.16 on 2026-07-18 20:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attraction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(unique=True)),
                ("subtitle", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("祠堂", "祠堂"),
                            ("桥", "桥"),
                            ("水岸", "水岸"),
                            ("码头", "码头"),
                            ("巷", "巷"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "depth_level",
                    models.SmallIntegerField(
                        choices=[(1, "基础展示"), (2, "深度闭环")], default=1
                    ),
                ),
                ("cover_image_url", models.TextField()),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                ("display_order", models.SmallIntegerField(default=0)),
                (
                    "status",
                    models.SmallIntegerField(choices=[(0, "下架"), (1, "启用")], default=1),
                ),
            ],
            options={
                "db_table": "attractions",
                "ordering": ("display_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20, unique=True)),
                ("icon", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "themes",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="VisitorSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_active_at", models.DateTimeField(auto_now=True)),
                ("preference_tags", models.JSONField(blank=True, default=list)),
            ],
            options={
                "db_table": "visitor_sessions",
                "ordering": ("-last_active_at",),
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("zone_name", models.CharField(max_length=20)),
                (
                    "center_latitude",
                    models.DecimalField(decimal_places=8, max_digits=10),
                ),
                (
                    "center_longitude",
                    models.DecimalField(decimal_places=8, max_digits=11),
                ),
                ("visual_cue", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "zones",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="StoryContent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("full_text", models.TextField()),
                ("audio_script", models.TextField()),
                ("fun_fact", models.CharField(max_length=200)),
                ("version", models.SmallIntegerField(default=1)),
                (
                    "attraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_contents",
                        to="main.attraction",
                    ),
                ),
            ],
            options={
                "db_table": "story_contents",
                "ordering": ("attraction_id", "-version"),
            },
        ),
        migrations.CreateModel(
            name="AudioAsset",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("file_name", models.CharField(max_length=100)),
                ("file_url", models.TextField()),
                ("duration_seconds", models.IntegerField()),
                ("language", models.CharField(default="zh-CN", max_length=10)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_assets",
                        to="main.storycontent",
                    ),
                ),
            ],
            options={
                "db_table": "audio_assets",
                "ordering": ("content_id", "id"),
            },
        ),
        migrations.CreateModel(
            name="AttractionTheme",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "attraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_links",
                        to="main.attraction",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attraction_links",
                        to="main.theme",
                    ),
                ),
            ],
            options={
                "db_table": "attraction_themes",
                "ordering": ("attraction_id", "theme_id"),
            },
        ),
        migrations.CreateModel(
            name="Touchpoint",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("trigger_code", models.CharField(max_length=20, unique=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[("qr", "二维码"), ("nfc", "NFC"), ("simulate", "模拟")],
                        max_length=10,
                    ),
                ),
                ("physical_location", models.CharField(max_length=100)),
                (
                    "attraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="touchpoints",
                        to="main.attraction",
                    ),
                ),
            ],
            options={
                "db_table": "touchpoints",
                "ordering": ("attraction_id", "trigger_code"),
            },
        ),
        migrations.CreateModel(
            name="Itinerary",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("zone_sequence", models.JSONField(default=list)),
                ("attraction_sequence", models.JSONField(default=list)),
                ("narrative_bridge", models.JSONField(default=dict)),
                ("total_estimated_minutes", models.IntegerField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itineraries",
                        to="main.visitorsession",
                    ),
                ),
            ],
            options={
                "db_table": "itineraries",
                "ordering": ("-generated_at",),
            },
        ),
        migrations.CreateModel(
            name="Footprint",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("audio_played", models.BooleanField(default=False)),
                (
                    "attraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="footprints",
                        to="main.attraction",
                    ),
                ),
                (
                    "itinerary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="footprints",
                        to="main.itinerary",
                    ),
                ),
                (
                    "touchpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="footprints",
                        to="main.touchpoint",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="footprints",
                        to="main.visitorsession",
                    ),
                ),
            ],
            options={
                "db_table": "footprints",
                "ordering": ("-triggered_at",),
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="main.attraction",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="main.visitorsession",
                    ),
                ),
            ],
            options={
                "db_table": "favorites",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="visitorsession",
            name="last_known_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visitor_sessions",
                to="main.zone",
            ),
        ),
        migrations.AddField(
            model_name="attraction",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attractions",
                to="main.zone",
            ),
        ),
        migrations.CreateModel(
            name="AttractionPath",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("distance_meters", models.IntegerField()),
                ("estimated_minutes", models.IntegerField()),
                ("is_scenic_route", models.BooleanField(default=False)),
                (
                    "from_attraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_paths",
                        to="main.attraction",
                    ),
                ),
                (
                    "to_attraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_paths",
                        to="main.attraction",
                    ),
                ),
            ],
            options={
                "db_table": "attraction_paths",
                "ordering": ("from_attraction_id", "to_attraction_id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("from_attraction", "to_attraction"),
                        name="attraction_paths_pair_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("from_attraction", models.F("to_attraction")),
                            _negated=True,
                        ),
                        name="attraction_paths_distinct_nodes",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("distance_meters__gte", 0)),
                        name="attraction_paths_distance_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("estimated_minutes__gte", 0)),
                        name="attraction_paths_minutes_nonnegative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HiddenDetail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("detail_text", models.CharField(max_length=300)),
                ("poi_latitude", models.DecimalField(decimal_places=8, max_digits=10)),
                ("poi_longitude", models.DecimalField(decimal_places=8, max_digits=11)),
                ("trigger_distance_meters", models.SmallIntegerField()),
                (
                    "attraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hidden_details",
                        to="main.attraction",
                    ),
                ),
            ],
            options={
                "db_table": "hidden_details",
                "ordering": ("attraction_id", "id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("trigger_distance_meters__gt", 0)),
                        name="hidden_details_trigger_distance_positive",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="storycontent",
            constraint=models.UniqueConstraint(
                fields=("attraction", "version"),
                name="story_contents_attraction_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="storycontent",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="story_contents_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="audioasset",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration_seconds__gte", 0)),
                name="audio_assets_duration_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="attractiontheme",
            constraint=models.UniqueConstraint(
                fields=("attraction", "theme"), name="attraction_themes_pair_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="itinerary",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_estimated_minutes__gte", 0)),
                name="itineraries_minutes_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("session", "attraction"),
                name="favorites_session_attraction_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="attraction",
            constraint=models.CheckConstraint(
                condition=models.Q(("depth_level__in", [1, 2])),
                name="attractions_depth_level_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="attraction",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", [0, 1])),
                name="attractions_status_valid",
            ),
        ),
    ]
