# Generated by Django 5.2.16 on 2026-07-18 21:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attraction",
            options={
                "ordering": ("display_order", "id"),
                "verbose_name": "景点",
                "verbose_name_plural": "景点管理",
            },
        ),
        migrations.AlterModelOptions(
            name="attractionpath",
            options={
                "ordering": ("from_attraction_id", "to_attraction_id"),
                "verbose_name": "景点路径",
                "verbose_name_plural": "景点路径",
            },
        ),
        migrations.AlterModelOptions(
            name="attractiontheme",
            options={
                "ordering": ("attraction_id", "theme_id"),
                "verbose_name": "景点主题标签",
                "verbose_name_plural": "景点主题标签",
            },
        ),
        migrations.AlterModelOptions(
            name="audioasset",
            options={
                "ordering": ("content_id", "id"),
                "verbose_name": "音频资源",
                "verbose_name_plural": "音频资源",
            },
        ),
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "故事收藏",
                "verbose_name_plural": "故事收藏",
            },
        ),
        migrations.AlterModelOptions(
            name="footprint",
            options={
                "ordering": ("-triggered_at",),
                "verbose_name": "足迹触发日志",
                "verbose_name_plural": "足迹触发日志",
            },
        ),
        migrations.AlterModelOptions(
            name="hiddendetail",
            options={
                "ordering": ("attraction_id", "id"),
                "verbose_name": "隐藏彩蛋",
                "verbose_name_plural": "沿途隐藏彩蛋",
            },
        ),
        migrations.AlterModelOptions(
            name="itinerary",
            options={
                "ordering": ("-generated_at",),
                "verbose_name": "专属路线",
                "verbose_name_plural": "专属路线",
            },
        ),
        migrations.AlterModelOptions(
            name="storycontent",
            options={
                "ordering": ("attraction_id", "-version"),
                "verbose_name": "故事内容",
                "verbose_name_plural": "故事内容",
            },
        ),
        migrations.AlterModelOptions(
            name="theme",
            options={
                "ordering": ("id",),
                "verbose_name": "叙事主题",
                "verbose_name_plural": "叙事主题",
            },
        ),
        migrations.AlterModelOptions(
            name="touchpoint",
            options={
                "ordering": ("attraction_id", "trigger_code"),
                "verbose_name": "触点",
                "verbose_name_plural": "触点管理",
            },
        ),
        migrations.AlterModelOptions(
            name="visitorsession",
            options={
                "ordering": ("-last_active_at",),
                "verbose_name": "匿名游客会话",
                "verbose_name_plural": "匿名游客会话",
            },
        ),
        migrations.AlterModelOptions(
            name="zone",
            options={
                "ordering": ("id",),
                "verbose_name": "区域",
                "verbose_name_plural": "区域管理",
            },
        ),
        migrations.AlterField(
            model_name="attraction",
            name="cover_image_url",
            field=models.TextField(verbose_name="封面图地址"),
        ),
        migrations.AlterField(
            model_name="attraction",
            name="depth_level",
            field=models.SmallIntegerField(
                choices=[(1, "基础展示"), (2, "深度闭环")], default=1, verbose_name="展示深度"
            ),
        ),
        migrations.AlterField(
            model_name="attraction",
            name="display_order",
            field=models.SmallIntegerField(default=0, verbose_name="后台排序"),
        ),
        migrations.AlterField(
            model_name="attraction",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="attraction",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=10,
                null=True,
                verbose_name="纬度",
            ),
        ),
        migrations.AlterField(
            model_name="attraction",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=11,
                null=True,
                verbose_name="经度",
            ),
        ),
        migrations.AlterField(
            model_name="attraction",
            name="name",
            field=models.CharField(max_length=50, verbose_name="景点名称"),
        ),
        migrations.AlterField(
            model_name="attraction",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="URL 标识"),
        ),
        migrations.AlterField(
            model_name="attraction",
            name="status",
            field=models.SmallIntegerField(
                choices=[(0, "下架"), (1, "启用")], default=1, verbose_name="状态"
            ),
        ),
        migrations.AlterField(
            model_name="attraction",
            name="subtitle",
            field=models.CharField(max_length=100, verbose_name="副标题"),
        ),
        migrations.AlterField(
            model_name="attraction",
            name="type",
            field=models.CharField(
                choices=[
                    ("祠堂", "祠堂"),
                    ("桥", "桥"),
                    ("水岸", "水岸"),
                    ("码头", "码头"),
                    ("巷", "巷"),
                ],
                max_length=20,
                verbose_name="景点分类",
            ),
        ),
        migrations.AlterField(
            model_name="attraction",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attractions",
                to="main.zone",
                verbose_name="所属区域",
            ),
        ),
        migrations.AlterField(
            model_name="attractionpath",
            name="distance_meters",
            field=models.IntegerField(verbose_name="步行距离（米）"),
        ),
        migrations.AlterField(
            model_name="attractionpath",
            name="estimated_minutes",
            field=models.IntegerField(verbose_name="预计步行时间（分钟）"),
        ),
        migrations.AlterField(
            model_name="attractionpath",
            name="from_attraction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_paths",
                to="main.attraction",
                verbose_name="起点景点",
            ),
        ),
        migrations.AlterField(
            model_name="attractionpath",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="attractionpath",
            name="is_scenic_route",
            field=models.BooleanField(default=False, verbose_name="风景推荐路径"),
        ),
        migrations.AlterField(
            model_name="attractionpath",
            name="to_attraction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_paths",
                to="main.attraction",
                verbose_name="终点景点",
            ),
        ),
        migrations.AlterField(
            model_name="attractiontheme",
            name="attraction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="theme_links",
                to="main.attraction",
                verbose_name="景点",
            ),
        ),
        migrations.AlterField(
            model_name="attractiontheme",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="attractiontheme",
            name="theme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attraction_links",
                to="main.theme",
                verbose_name="叙事主题",
            ),
        ),
        migrations.AlterField(
            model_name="audioasset",
            name="content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audio_assets",
                to="main.storycontent",
                verbose_name="故事内容",
            ),
        ),
        migrations.AlterField(
            model_name="audioasset",
            name="duration_seconds",
            field=models.IntegerField(verbose_name="音频时长（秒）"),
        ),
        migrations.AlterField(
            model_name="audioasset",
            name="file_name",
            field=models.CharField(max_length=100, verbose_name="原始文件名"),
        ),
        migrations.AlterField(
            model_name="audioasset",
            name="file_url",
            field=models.TextField(verbose_name="音频文件地址"),
        ),
        migrations.AlterField(
            model_name="audioasset",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="audioasset",
            name="language",
            field=models.CharField(default="zh-CN", max_length=10, verbose_name="语言"),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="attraction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to="main.attraction",
                verbose_name="收藏景点",
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="收藏时间"),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to="main.visitorsession",
                verbose_name="游客会话",
            ),
        ),
        migrations.AlterField(
            model_name="footprint",
            name="attraction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="footprints",
                to="main.attraction",
                verbose_name="触发景点",
            ),
        ),
        migrations.AlterField(
            model_name="footprint",
            name="audio_played",
            field=models.BooleanField(default=False, verbose_name="音频是否完整播放"),
        ),
        migrations.AlterField(
            model_name="footprint",
            name="id",
            field=models.BigAutoField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="footprint",
            name="itinerary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="footprints",
                to="main.itinerary",
                verbose_name="所属路线",
            ),
        ),
        migrations.AlterField(
            model_name="footprint",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="footprints",
                to="main.visitorsession",
                verbose_name="游客会话",
            ),
        ),
        migrations.AlterField(
            model_name="footprint",
            name="touchpoint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="footprints",
                to="main.touchpoint",
                verbose_name="触发触点",
            ),
        ),
        migrations.AlterField(
            model_name="footprint",
            name="triggered_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="触发时间"),
        ),
        migrations.AlterField(
            model_name="hiddendetail",
            name="attraction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hidden_details",
                to="main.attraction",
                verbose_name="所属景点",
            ),
        ),
        migrations.AlterField(
            model_name="hiddendetail",
            name="detail_text",
            field=models.CharField(max_length=300, verbose_name="彩蛋文案"),
        ),
        migrations.AlterField(
            model_name="hiddendetail",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="hiddendetail",
            name="poi_latitude",
            field=models.DecimalField(
                decimal_places=8, max_digits=10, verbose_name="彩蛋纬度"
            ),
        ),
        migrations.AlterField(
            model_name="hiddendetail",
            name="poi_longitude",
            field=models.DecimalField(
                decimal_places=8, max_digits=11, verbose_name="彩蛋经度"
            ),
        ),
        migrations.AlterField(
            model_name="hiddendetail",
            name="trigger_distance_meters",
            field=models.SmallIntegerField(verbose_name="触发距离（米）"),
        ),
        migrations.AlterField(
            model_name="itinerary",
            name="attraction_sequence",
            field=models.JSONField(default=list, verbose_name="景点顺序"),
        ),
        migrations.AlterField(
            model_name="itinerary",
            name="generated_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="生成时间"),
        ),
        migrations.AlterField(
            model_name="itinerary",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="itinerary",
            name="is_completed",
            field=models.BooleanField(default=False, verbose_name="是否完成"),
        ),
        migrations.AlterField(
            model_name="itinerary",
            name="narrative_bridge",
            field=models.JSONField(default=dict, verbose_name="叙事过渡提示"),
        ),
        migrations.AlterField(
            model_name="itinerary",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itineraries",
                to="main.visitorsession",
                verbose_name="游客会话",
            ),
        ),
        migrations.AlterField(
            model_name="itinerary",
            name="total_estimated_minutes",
            field=models.IntegerField(verbose_name="预计总时长（分钟）"),
        ),
        migrations.AlterField(
            model_name="itinerary",
            name="zone_sequence",
            field=models.JSONField(default=list, verbose_name="区域顺序"),
        ),
        migrations.AlterField(
            model_name="storycontent",
            name="attraction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="story_contents",
                to="main.attraction",
                verbose_name="所属景点",
            ),
        ),
        migrations.AlterField(
            model_name="storycontent",
            name="audio_script",
            field=models.TextField(verbose_name="语音讲解脚本"),
        ),
        migrations.AlterField(
            model_name="storycontent",
            name="full_text",
            field=models.TextField(verbose_name="完整历史故事"),
        ),
        migrations.AlterField(
            model_name="storycontent",
            name="fun_fact",
            field=models.CharField(max_length=200, verbose_name="一句冷知识"),
        ),
        migrations.AlterField(
            model_name="storycontent",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="storycontent",
            name="version",
            field=models.SmallIntegerField(default=1, verbose_name="内容版本号"),
        ),
        migrations.AlterField(
            model_name="theme",
            name="description",
            field=models.CharField(max_length=100, verbose_name="主题简介"),
        ),
        migrations.AlterField(
            model_name="theme",
            name="icon",
            field=models.CharField(max_length=50, verbose_name="图标类名"),
        ),
        migrations.AlterField(
            model_name="theme",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="name",
            field=models.CharField(max_length=20, unique=True, verbose_name="主题名称"),
        ),
        migrations.AlterField(
            model_name="touchpoint",
            name="attraction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="touchpoints",
                to="main.attraction",
                verbose_name="关联景点",
            ),
        ),
        migrations.AlterField(
            model_name="touchpoint",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="touchpoint",
            name="physical_location",
            field=models.CharField(max_length=100, verbose_name="实体位置描述"),
        ),
        migrations.AlterField(
            model_name="touchpoint",
            name="trigger_code",
            field=models.CharField(max_length=20, unique=True, verbose_name="唯一触发码"),
        ),
        migrations.AlterField(
            model_name="touchpoint",
            name="trigger_type",
            field=models.CharField(
                choices=[("qr", "二维码"), ("nfc", "NFC"), ("simulate", "模拟")],
                max_length=10,
                verbose_name="触发类型",
            ),
        ),
        migrations.AlterField(
            model_name="visitorsession",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="首次访问时间"),
        ),
        migrations.AlterField(
            model_name="visitorsession",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="会话 ID",
            ),
        ),
        migrations.AlterField(
            model_name="visitorsession",
            name="last_active_at",
            field=models.DateTimeField(auto_now=True, verbose_name="最后活跃时间"),
        ),
        migrations.AlterField(
            model_name="visitorsession",
            name="last_known_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visitor_sessions",
                to="main.zone",
                verbose_name="上次所在区域",
            ),
        ),
        migrations.AlterField(
            model_name="visitorsession",
            name="preference_tags",
            field=models.JSONField(blank=True, default=list, verbose_name="兴趣标签"),
        ),
        migrations.AlterField(
            model_name="zone",
            name="center_latitude",
            field=models.DecimalField(
                decimal_places=8, max_digits=10, verbose_name="中心纬度"
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="center_longitude",
            field=models.DecimalField(
                decimal_places=8, max_digits=11, verbose_name="中心经度"
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="description",
            field=models.CharField(max_length=200, verbose_name="区域氛围描述"),
        ),
        migrations.AlterField(
            model_name="zone",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="visual_cue",
            field=models.CharField(max_length=100, verbose_name="视觉地标提示"),
        ),
        migrations.AlterField(
            model_name="zone",
            name="zone_name",
            field=models.CharField(max_length=20, verbose_name="区域名称"),
        ),
    ]
