# Generated by Django 5.2.16 on 2026-07-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_attraction_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attraction",
            name="map_x_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="手绘地图横坐标（%）",
            ),
        ),
        migrations.AddField(
            model_name="attraction",
            name="map_y_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="手绘地图纵坐标（%）",
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="center_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=10,
                null=True,
                verbose_name="中心纬度",
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="center_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=11,
                null=True,
                verbose_name="中心经度",
            ),
        ),
        migrations.AddConstraint(
            model_name="attraction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("map_x_percent__isnull", True),
                    models.Q(("map_x_percent__gte", 0), ("map_x_percent__lte", 100)),
                    _connector="OR",
                ),
                name="attractions_map_x_percent_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="attraction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("map_y_percent__isnull", True),
                    models.Q(("map_y_percent__gte", 0), ("map_y_percent__lte", 100)),
                    _connector="OR",
                ),
                name="attractions_map_y_percent_valid",
            ),
        ),
    ]
