# Generated by Django 5.2.16 on 2026-07-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_attraction_map_x_percent_attraction_map_y_percent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itinerary",
            name="duration_limit_minutes",
            field=models.IntegerField(default=60, verbose_name="时长上限（分钟）"),
        ),
        migrations.AddField(
            model_name="itinerary",
            name="planning_mode",
            field=models.CharField(
                default="relaxed", max_length=10, verbose_name="规划模式"
            ),
        ),
        migrations.AddField(
            model_name="itinerary",
            name="preference_tags_snapshot",
            field=models.JSONField(default=list, verbose_name="兴趣标签快照"),
        ),
        migrations.AddField(
            model_name="itinerary",
            name="score",
            field=models.IntegerField(default=0, verbose_name="路线评分"),
        ),
    ]
