# Generated by Django 5.2.16 on 2026-07-19 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_itinerary_duration_limit_minutes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitorEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_type", models.CharField(max_length=50, verbose_name="事件类型")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="补充数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="记录时间"),
                ),
                (
                    "attraction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="main.attraction",
                        verbose_name="关联景点",
                    ),
                ),
                (
                    "itinerary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="main.itinerary",
                        verbose_name="关联路线",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="main.visitorsession",
                        verbose_name="游客会话",
                    ),
                ),
            ],
            options={
                "verbose_name": "游客行为事件",
                "verbose_name_plural": "游客行为事件",
                "db_table": "visitor_events",
                "ordering": ("-created_at",),
            },
        ),
    ]
