# Generated by Django 5.2.16 on 2026-07-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_visitorevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalVoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                (
                    "original_file_name",
                    models.CharField(max_length=100, unique=True, verbose_name="原始文件名"),
                ),
                ("file_url", models.TextField(verbose_name="音频文件地址")),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(verbose_name="音频时长（秒）"),
                ),
                (
                    "language",
                    models.CharField(default="local", max_length=20, verbose_name="语言"),
                ),
                (
                    "language_label",
                    models.CharField(
                        default="当地讲述", max_length=20, verbose_name="语言标签"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="后台排序"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
            ],
            options={
                "verbose_name": "当地声音",
                "verbose_name_plural": "当地声音",
                "db_table": "local_voices",
                "ordering": ("display_order", "id"),
            },
        ),
    ]
