# Generated by Django 5.2.16 on 2026-07-20 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_localvoice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="会话标题")),
                (
                    "default_days",
                    models.PositiveSmallIntegerField(default=30, verbose_name="默认统计天数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_conversations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="后台员工",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 运营分析会话",
                "verbose_name_plural": "AI 运营分析会话",
                "db_table": "analytics_conversations",
                "ordering": ("-updated_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="AnalyticsTurn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("question", models.TextField(verbose_name="管理员问题")),
                (
                    "answer",
                    models.JSONField(blank=True, default=dict, verbose_name="AI 结构化回答"),
                ),
                (
                    "metrics_snapshot",
                    models.JSONField(blank=True, default=dict, verbose_name="匿名指标快照"),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="模型"
                    ),
                ),
                (
                    "days",
                    models.PositiveSmallIntegerField(default=30, verbose_name="统计天数"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=12,
                        verbose_name="状态",
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="安全错误代码"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提问时间"),
                ),
                (
                    "answered_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="回答时间"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="main.analyticsconversation",
                        verbose_name="所属会话",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 运营分析轮次",
                "verbose_name_plural": "AI 运营分析轮次",
                "db_table": "analytics_turns",
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="analyticsconversation",
            index=models.Index(
                fields=["owner", "-updated_at"], name="analytics_owner_updated_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="analyticsconversation",
            constraint=models.CheckConstraint(
                condition=models.Q(("default_days__in", (7, 30, 90))),
                name="analytics_conversation_days_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsturn",
            index=models.Index(
                fields=["conversation", "created_at"], name="analytics_conv_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="analyticsturn",
            constraint=models.CheckConstraint(
                condition=models.Q(("days__in", (7, 30, 90))),
                name="analytics_turn_days_valid",
            ),
        ),
    ]
