"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-etxlx65knef%tqx15#w+0mtdr!2%#=17jxv$9pbv(9oc7z6xy)",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
    if host.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    "main.apps.MainConfig",
    "simpleui",
    "rest_framework",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "config.middleware.SameOriginFrameMiddleware",
]

if not DEBUG:
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "frontend" / "dist"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if not DEBUG and not os.environ.get("DATABASE_URL"):
    raise ImproperlyConfigured("DATABASE_URL is required when DEBUG=False.")

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "frontend" / "dist",
    BASE_DIR / "frontend" / "public",
    BASE_DIR / "frontend" / "src" / "bijiang" / "assets",
]

if not DEBUG:
    STORAGES = {
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "3600"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# SimpleUI removes Django's built-in frame middleware at startup. The custom
# equivalent above preserves SAMEORIGIN, while HSTS preload stays off until the
# new domain has operated exclusively over HTTPS for a sustained period.
SILENCED_SYSTEM_CHECKS = ["security.W002", "security.W021"]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.AllowAny"],
    "DEFAULT_RENDERER_CLASSES": ["rest_framework.renderers.JSONRenderer"],
}

DEEPSEEK_API_KEY = os.environ.get("DEEPSEEK_API_KEY", "")
DEEPSEEK_MODEL = os.environ.get("DEEPSEEK_MODEL", "deepseek-chat")
DEEPSEEK_BASE_URL = os.environ.get("DEEPSEEK_BASE_URL", "https://api.deepseek.com")
DEEPSEEK_TIMEOUT_SECONDS = int(os.environ.get("DEEPSEEK_TIMEOUT_SECONDS", "30"))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# SimpleUI admin branding and domain navigation.
SIMPLEUI_HOME_TITLE = "碧江文旅数据后台"
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False
SIMPLEUI_DEFAULT_THEME = "admin.lte.css"
SIMPLEUI_CONFIG = {
    "system_keep": False,
    "menus": [
        {
            "name": "数据概览",
            "icon": "fas fa-chart-line",
            "url": "/admin/data-overview/",
        },
        {
            "name": "内容资产库",
            "icon": "fas fa-book-open",
            "models": [
                {"name": "景点管理", "icon": "fas fa-map-marker-alt", "url": "/admin/main/attraction/"},
                {"name": "故事内容", "icon": "fas fa-align-left", "url": "/admin/main/storycontent/"},
                {"name": "音频资源", "icon": "fas fa-volume-up", "url": "/admin/main/audioasset/"},
                {"name": "叙事主题", "icon": "fas fa-tags", "url": "/admin/main/theme/"},
                {"name": "景点主题标签", "icon": "fas fa-link", "url": "/admin/main/attractiontheme/"},
                {"name": "沿途隐藏彩蛋", "icon": "fas fa-lightbulb", "url": "/admin/main/hiddendetail/"},
            ],
        },
        {
            "name": "空间与路线",
            "icon": "fas fa-route",
            "models": [
                {"name": "区域管理", "icon": "fas fa-map", "url": "/admin/main/zone/"},
                {"name": "景点路径", "icon": "fas fa-directions", "url": "/admin/main/attractionpath/"},
                {"name": "专属路线", "icon": "fas fa-project-diagram", "url": "/admin/main/itinerary/"},
            ],
        },
        {
            "name": "触点管理",
            "icon": "fas fa-qrcode",
            "models": [
                {"name": "二维码 / NFC 触点", "icon": "fas fa-broadcast-tower", "url": "/admin/main/touchpoint/"},
            ],
        },
        {
            "name": "游客行为",
            "icon": "fas fa-walking",
            "models": [
                {"name": "匿名游客会话", "icon": "fas fa-user-clock", "url": "/admin/main/visitorsession/"},
                {"name": "足迹触发日志", "icon": "fas fa-shoe-prints", "url": "/admin/main/footprint/"},
                {"name": "故事收藏", "icon": "fas fa-star", "url": "/admin/main/favorite/"},
            ],
        },
        {
            "name": "系统管理",
            "icon": "fas fa-user-shield",
            "models": [
                {"name": "管理员", "icon": "fas fa-users", "url": "/admin/auth/user/"},
                {"name": "权限组", "icon": "fas fa-users-cog", "url": "/admin/auth/group/"},
            ],
        },
    ],
}
